networks:
  backend:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      backend:
        aliases:
          - "rabbitmq"

  spring-cloud-stream-service:
    image: drs/scs:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  spring-cloud-stream-consumer:
    image: drs/scs-consumer:latest
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  monitor:
    image: drs/monitor:latest
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  spring-cloud-stream-dlx:
    image: drs/scs-dlx:latest
    ports:
      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

